### ISSUE TITLE
Proper Way to Create a 4.9 Branch

### ISSUE THREAD

**Issue by cramaker** [GalliumOS/linux#2]
Hey there,

I've recently forked this repo and started altering the diffs to accommodate the 4.9 version of the Linux kernel. I just did a clean branch creation from the original master, and it occurred to me that some valuable history and attributions from the 4.7.2 branch might be lost.

Do you have a preferred way to proceed - either forking from 4.7.2 or perhaps merging 4.7.2 back into master and I shall fork from there? Please let me know your thoughts - thanks!

**Comment by reynhout** [comment]
@cramaker The way I do it is to fork master to a versioned branch ("v4.9"), then commit the whole clean mainline. Then re-add the patches to the `galliumos` directory. You'll see that in the other versioned branches, along with some notes.

I have a 4.9 branch locally already, but I haven't begun porting the patches (or determining what porting will be necessary). If you want to wait for me to push that branch, you can just pull it down and not worry about the logistical/process parts.

**Comment by cramaker** [comment]
I've already been following in your footsteps with a barebones branch that I pushed up with just the kernel. (seen here https://github.com/cramaker/linux/tree/v4.9.0) 

I've made some local modifications too (mostly to aufs & some of the patches have made it into mainline)

**Comment by reynhout** [comment]
@cramaker OK, awesome. What hardware are you testing on btw?

**Comment by cramaker** [comment]
@reynhout I've got an Acer Chromebook 14 which has the Braswell architecture, hence my interest in the latest kernel. 

If you don't mind me asking here, how did you generate the add-bfq.diff? I see four individual patch files at http://algogroup.unimore.it/people/paolo/disk_sched/patches/4.7.0-v8r3/ - did you cat these together in some fashion?

**Comment by reynhout** [comment]
@cramaker I created `add-bfq.diff` by adding each of the (three?) BFQ patches, then diffing the new tree.

I don't think the BFQ patches for 4.9 have been released yet, but they can be added later.

**Comment by reynhout** [comment]
PS: I don't think the 4.9 mainline kernel will solve any issues on the Braswell models directly, but it definitely makes sense to start working on custom patches from there.
