### ISSUE TITLE
Please Create v4.7.10 Branch for Pull Request

### ISSUE THREAD

**Issue by cramaker** [GalliumOS/linux#3]
Hey there,

In my quest to get a working 4.9 (and 4.8...) kernel, I've developed a working 4.7.10 branch (https://github.com/cramaker/linux/tree/v4.7.10)  that is currently built and running on my Acer Chromebook 14. If you can create a bare v4.7.10 branch in this repository, I'll open up a pull request so we can have the final edition of the 4.7 series ready for GalliumOS

**Comment by reynhout** [comment]
Branched. :)
