### ISSUE TITLE
Enable EXT4 filesystem encryption

### ISSUE THREAD

**Issue by lwbt** [GalliumOS/linux#5]
Please enable native filesystem encryption for EXT4 (CONFIG_EXT4_FS_ENCRYPTION). I recompiled the kernel on my REKS and got it working with an external SD card following these instructions: http://askubuntu.com/a/689036/40581

**Comment by reynhout** [comment]
Please repost this in the tracker for galliumos-distro, so it doesn't get lost. Thanks!

**Comment by reynhout** [comment]
This config is added in kernels 4.8.17-galliumos4 and 4.9.4-galliumos2.
